
# Redirect HTTP -> HTTPS
server {
    listen 0.0.0.0:80;
    server_name jf.customdomain.com;

    client_max_body_size 2000M;
    client_body_buffer_size 128k;

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server for Jellyfin
server {
    listen 0.0.0.0:443 ssl;
    http2 on;
    server_name jf.customdomain.com;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 2000M;
    client_body_buffer_size 128k;
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_pass http://jellyfin:8096/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
