name: media-server CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Docker Compose
      run: |
        docker compose --version

    - name: Start Stack
      run: |
        # Create necessary directories
        mkdir -p ./data/immich ./data/plexmediaserver ./data/ssl ./data/duplicati
        # Use sample config files for testing
        sed -i s@./data/immich.conf@./sample-configs/immich.conf@g docker-compose.yml
        docker compose --env-file ./sample-configs/.env up -d
        sleep 15  # adjust for slowest service startup

    - name: Show Container Status
      run: |
        docker compose ps

    - name: Health Check All Services
      run: |
        # Check if any container is unhealthy
        unhealthy=$(docker ps --filter 'health=unhealthy' --format '{{.Names}}')
        if [ ! -z "$unhealthy" ]; then
          echo "Unhealthy container(s): $unhealthy"
          exit 1
        fi

    - name: Container Logs (on failure)
      if: failure()
      run: |
        docker compose logs

    - name: Tear Down Stack
      run: |
        docker compose down -v --remove-orphans
